### ISSUE TITLE
DOMException: Failed to construct 'RTCPeerConnection': ICE server parse failed

### ISSUE THREAD

**Issue by mijorus** [suda/webmic#19]
Hi, 
I wanted to give this app a try but I cannot see the speaker.

These are the errors I am getting in the console:

```
ipfs.min.js:2 
        
       WebSocket connection to 'wss://sfo-3.bootstrap.libp2p.io/p2p/QmSoLPppuBtQSGwKDZT2M73ULpjvfd3axxxxxxxxxxxxxxxxx' failed

bundle.min.js:1 
        
       DOMException: Failed to construct 'RTCPeerConnection': ICE server parse failed
```

I am using  Microsoft Edge, on my PC and Firefox on my phone

**Comment by suda** [comment]
Hi Lorenzo, sorry for not attending this sooner. Looks like the ICE server format changed and the port number is now required.
I just released[`v0.1.1`](https://github.com/suda/webmic/releases/tag/v0.1.1) which should fix it. You can go to https://webmic.suda.pl and see it for yourself :)
